#[cfg(feature = "cli")]
pub mod compiler;
pub mod blaze;
pub mod diagnostics;
pub mod lexer;
pub mod native_std;
pub mod package_manager;
pub mod parser;
pub mod runner;
pub mod stdlib;
pub mod test_engine;
pub mod typechecker;
pub mod utils;
pub mod vm;
